apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: my-namespace

resources:
  - ../../base/prometheus-alerts

patches:
  - target:
      kind: PrometheusRule
    path: alerting-rules-test.yaml
