apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: my-namespace

openapi:
  path: com.coreos.monitoring.v1.PrometheusRule.yaml

resources:
  - ../../base/prometheus-alerts

patches:
  - path: alerting-rules-test.yaml
